name: Test CI

on:
  push:
    branches:
      - master
      - test-run
      - release/*

jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run Build
        run: npm run build
